#!/usr/bin/env zsh

echo "The production build and deploy capabilities provided by:"
echo " "
echo "  MCP Full Release"
echo "  ----------------"
echo "   a. git pull"
echo "   a. env MIX_ENV=prod mix release mcp"
echo "   b. extra/install-and-start.sh"
echo " "
echo "  MCR Full Release"
echo "  ----------------"
echo "   a. extra/deploy-mcr-firmware.sh"
echo " "
echo "  NOTES:"
echo "   a. Build and deploy scripts no longer automatically git pull"
echo "      so don't forgot to do so if needed."
echo "   b. The MCR Full Release script deploys the firmware to htdocs"
echo "      and creates the latest-* symbolic links.  Use Remote.ota_update/1"
echo "      to trigger the firmware update."
exit 1
