#!/bin/zsh

	if [[ $1 == "--clean" ]]; then
		clean=1
	fi

	setopt local_options rm_star_silent
	
	# configuration variables
	merc_base=/usr/local/mercurial
	merc_bin=$merc_base/bin
	release=/run/merc/mcp.tar.gz

	if [[ -f $release ]]; then
		$merc_bin/mcp ping 1> /dev/null 2>&1
		if [[ $? -eq 0 ]]; then
			print -n "stopping merc before install..." && $merc_base/bin/mcp stop 1> /dev/null 2>&1 && print " done."
		fi

		if [[ $? -eq 0 ]]; then
			if [[ $clean -eq 1 ]]; then
				print -n "cleaning up $merc_base..." && rm -rf $merc_base/* && print " done."
			else
				print "won't clean existing release, use --clean to do so"
			fi

			print -n "untarring $release..." && tar -C $merc_base -xf $release && print " done." 

				if [[ $? -eq 0 ]]; then
					print -n "removing deploy tar..." && rm -f $release && print " done."
					print "starting merc then running tail. (use CTRL+C to stop)"

					env PORT=4009 mcp start
					sleep 2
					exec tail --lines=100 -f $merc_base/var/log/erlang.*(om[1])
				fi	
		fi
	else
		print "deploy tar $release doesn't exist, doing nothing."
		return 1	
	fi
}
