defmodule Seed.Mixtanks do
  @moduledoc """
  """

def mixtanks(env) when env in [:dev, :test] do
  [%Mixtank{name: "testmix change",
    description: "reefwater change mode (full pump, no air)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "sw1",
    air_sw: "sw2",
    air_run_ms: 0, air_idle_ms: 3_600_000,
    pump_sw: "sw3",
    pump_run_ms: 3_600_000, pump_idle_ms: 0,
    state_at: Timex.now()},
  %Mixtank{name: "testmix fill",
    description: "reefwater fill mode (pump only, no air)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "sw1",
    air_sw: "sw2",
    air_run_ms: 0, air_idle_ms: 3_600_000,
    pump_sw: "sw3",
    pump_run_ms: 60 * 60 * 1000, pump_idle_ms: 60 * 1000,
    state_at: Timex.now()},
  %Mixtank{name: "testmix minimal",
    description: "reefwater minimal mode (pump minimal, air minimal)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "sw1",
    air_sw: "sw2",
    air_run_ms: 10 * 60 * 1000, air_idle_ms: 4 * 60 * 60 * 1000,
    pump_sw: "sw3",
    pump_run_ms: 10 * 60 * 1000, pump_idle_ms: 4 * 60 * 60 * 1000,
    state_at: Timex.now()},
  %Mixtank{name: "testmix mix",
    description: "reefwater mix mode (pump max, air max)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "sw1",
    air_sw: "sw2",
    air_run_ms: 4 * 60 * 60 * 1000, air_idle_ms: 5 * 60 * 1000,
    pump_sw: "sw3",
    pump_run_ms: 4 * 60 * 60 * 1000, pump_idle_ms: 5 * 60 * 1000,
    state_at: Timex.now()}]
end

def mixtanks(:prod) do
  [%Mixtank{name: "reefmix change",
    description: "reefwater change mode (full pump, no air)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "mixtank_heater",
    air_sw: "mixtank_air",
    air_run_ms: 0, air_idle_ms: 3_600_000,
    pump_sw: "mixtank_pump",
    pump_run_ms: 3_600_000, pump_idle_ms: 0,
    state_at: Timex.now()},
  %Mixtank{name: "reefmix fill",
    description: "reefwater fill mode (pump only, no air)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "mixtank_heater",
    air_sw: "mixtank_air",
    air_run_ms: 0, air_idle_ms: 3_600_000,
    pump_sw: "mixtank_pump",
    pump_run_ms: 60 * 60 * 1000, pump_idle_ms: 60 * 1000,
    state_at: Timex.now()},
  %Mixtank{name: "reefmix minimal",
    description: "reefwater minimal mode (pump minimal, air minimal)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "mixtank_heater",
    air_sw: "mixtank_air",
    air_run_ms: 10 * 60 * 1000, air_idle_ms: 4 * 60 * 60 * 1000,
    pump_sw: "mixtank_pump",
    pump_run_ms: 10 * 60 * 1000, pump_idle_ms: 4 * 60 * 60 * 1000,
    state_at: Timex.now()},
  %Mixtank{name: "reefmix mix",
    description: "reefwater mix mode (pump max, air max)",
    enable: :false,
    sensor: "mixtank", ref_sensor: "display_tank",
    heat_sw: "mixtank_heater",
    air_sw: "mixtank_air",
    air_run_ms: 4 * 60 * 60 * 1000, air_idle_ms: 5 * 60 * 1000,
    pump_sw: "mixtank_pump",
    pump_run_ms: 4 * 60 * 60 * 1000, pump_idle_ms: 5 * 60 * 1000,
    state_at: Timex.now()}]
end

end
